// Generated by scripts/generate-cms-taxonomy.mjs.
// Do not edit by hand. Run `npm run cms:taxonomy` after adding many new tags.

export type CmsTaxonomyOption = {
  label: string;
  value: string;
  count: number;
};

export const postCategorySuggestions = [
  {
    label: "Amazon (1)",
    value: "Amazon",
    count: 1,
  },
  {
    label: "版本更新",
    value: "版本更新",
    count: 0,
  },
  {
    label: "博客建设",
    value: "博客建设",
    count: 0,
  },
  {
    label: "建站笔记",
    value: "建站笔记",
    count: 0,
  },
  {
    label: "前端开发",
    value: "前端开发",
    count: 0,
  },
  {
    label: "视觉主题",
    value: "视觉主题",
    count: 0,
  },
  {
    label: "AI 搜索",
    value: "AI 搜索",
    count: 0,
  },
] satisfies CmsTaxonomyOption[];

export const postSubcategorySuggestions = [
  {
    label: "亚马逊 (1)",
    value: "亚马逊",
    count: 1,
  },
  {
    label: "发布流程",
    value: "发布流程",
    count: 0,
  },
  {
    label: "配色",
    value: "配色",
    count: 0,
  },
  {
    label: "示例项目",
    value: "示例项目",
    count: 0,
  },
  {
    label: "AstroPaper",
    value: "AstroPaper",
    count: 0,
  },
  {
    label: "GEO",
    value: "GEO",
    count: 0,
  },
] satisfies CmsTaxonomyOption[];

export const postTagSuggestions = [
  {
    label: "docs (7)",
    value: "docs",
    count: 7,
  },
  {
    label: "release (6)",
    value: "release",
    count: 6,
  },
  {
    label: "TypeScript (3)",
    value: "TypeScript",
    count: 3,
  },
  {
    label: "Astro (2)",
    value: "Astro",
    count: 2,
  },
  {
    label: "color-schemes (2)",
    value: "color-schemes",
    count: 2,
  },
  {
    label: "FAQ (2)",
    value: "FAQ",
    count: 2,
  },
  {
    label: "博客 (1)",
    value: "博客",
    count: 1,
  },
  {
    label: "收藏 (1)",
    value: "收藏",
    count: 1,
  },
  {
    label: "写作 (1)",
    value: "写作",
    count: 1,
  },
  {
    label: "Amazon (1)",
    value: "Amazon",
    count: 1,
  },
  {
    label: "astro (1)",
    value: "astro",
    count: 1,
  },
  {
    label: "blog (1)",
    value: "blog",
    count: 1,
  },
  {
    label: "Blog (1)",
    value: "Blog",
    count: 1,
  },
  {
    label: "configuration (1)",
    value: "configuration",
    count: 1,
  },
  {
    label: "ContextAPI (1)",
    value: "ContextAPI",
    count: 1,
  },
  {
    label: "GEO (1)",
    value: "GEO",
    count: 1,
  },
  {
    label: "HeadlessCMS (1)",
    value: "HeadlessCMS",
    count: 1,
  },
  {
    label: "JavaScript (1)",
    value: "JavaScript",
    count: 1,
  },
  {
    label: "NextJS (1)",
    value: "NextJS",
    count: 1,
  },
  {
    label: "ReactJS (1)",
    value: "ReactJS",
    count: 1,
  },
  {
    label: "SEO (1)",
    value: "SEO",
    count: 1,
  },
  {
    label: "Styled-Components (1)",
    value: "Styled-Components",
    count: 1,
  },
  {
    label: "TailwindCSS (1)",
    value: "TailwindCSS",
    count: 1,
  },
] satisfies CmsTaxonomyOption[];

export const resourceCategorySuggestions = [
  {
    label: "游戏 (1)",
    value: "游戏",
    count: 1,
  },
  {
    label: "建站笔记",
    value: "建站笔记",
    count: 0,
  },
  {
    label: "前端开发",
    value: "前端开发",
    count: 0,
  },
  {
    label: "游戏资料",
    value: "游戏资料",
    count: 0,
  },
  {
    label: "资源收藏",
    value: "资源收藏",
    count: 0,
  },
  {
    label: "AI 搜索",
    value: "AI 搜索",
    count: 0,
  },
] satisfies CmsTaxonomyOption[];

export const resourceSubcategorySuggestions = [
  {
    label: "无畏契约 (1)",
    value: "无畏契约",
    count: 1,
  },
  {
    label: "代码仓库",
    value: "代码仓库",
    count: 0,
  },
  {
    label: "工具",
    value: "工具",
    count: 0,
  },
  {
    label: "课程",
    value: "课程",
    count: 0,
  },
  {
    label: "视频",
    value: "视频",
    count: 0,
  },
  {
    label: "书签",
    value: "书签",
    count: 0,
  },
  {
    label: "文章",
    value: "文章",
    count: 0,
  },
  {
    label: "游戏",
    value: "游戏",
    count: 0,
  },
] satisfies CmsTaxonomyOption[];

export const resourceSourceSuggestions = [
  {
    label: "抖音 (2)",
    value: "抖音",
    count: 2,
  },
  {
    label: "Bilibili (1)",
    value: "Bilibili",
    count: 1,
  },
  {
    label: "官方文档",
    value: "官方文档",
    count: 0,
  },
  {
    label: "GitHub",
    value: "GitHub",
    count: 0,
  },
  {
    label: "Product Hunt",
    value: "Product Hunt",
    count: 0,
  },
  {
    label: "YouTube",
    value: "YouTube",
    count: 0,
  },
] satisfies CmsTaxonomyOption[];

export const resourceTagSuggestions = [
  {
    label: "无畏契约 (3)",
    value: "无畏契约",
    count: 3,
  },
  {
    label: "瓦罗兰特 (2)",
    value: "瓦罗兰特",
    count: 2,
  },
  {
    label: "奥丁 (1)",
    value: "奥丁",
    count: 1,
  },
  {
    label: "黑梦 (1)",
    value: "黑梦",
    count: 1,
  },
  {
    label: "教程 (1)",
    value: "教程",
    count: 1,
  },
  {
    label: "奶妈 (1)",
    value: "奶妈",
    count: 1,
  },
  {
    label: "深海明珠 (1)",
    value: "深海明珠",
    count: 1,
  },
  {
    label: "视频 (1)",
    value: "视频",
    count: 1,
  },
  {
    label: "斯凯 (1)",
    value: "斯凯",
    count: 1,
  },
  {
    label: "贤者 (1)",
    value: "贤者",
    count: 1,
  },
] satisfies CmsTaxonomyOption[];
